---
- name: Check unpartitioned space
  shell: /sbin/parted /dev/mmcblk0 unit gb print free | grep 'Free Space' | tail -n1 | awk '{print $3}'
  register: unpartitioned
  changed_when: false

- name: Expand filesystem to fill disk
  command: raspi-config --expand-rootfs
  become: yes
  when: unpartitioned.stdout != "0.00GB"
  notify:
  - Restart
  - Wait for restart to finish

- name: Disable raspi-config
  script: scripts/disable-raspi-config.sh
  become: yes
  when: fs_expanded.stat.exists == False

- meta: flush_handlers
